/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.miniprojeto;

import java.awt.event.KeyEvent;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author anaju
 */
public class GerenciarTarefas extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarTarefas
     */
    public GerenciarTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVizualizar = new javax.swing.JButton();
        btnApagarTudo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAddTarefa = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPainel = new javax.swing.JTextArea();
        lbTotalTarefas = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlabel.setForeground(new java.awt.Color(0, 153, 153));
        jlabel.setText("Total de tarefas:");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnEditar.setBackground(new java.awt.Color(153, 255, 255));
        btnEditar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 60, 30));

        btnExcluir.setBackground(new java.awt.Color(153, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnExcluir.setText("Excluir ");
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 60, 30));

        btnVizualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnVizualizar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnVizualizar.setText("Vizualizar");
        btnVizualizar.setBorder(null);
        btnVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVizualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVizualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 30));

        btnApagarTudo.setBackground(new java.awt.Color(153, 255, 255));
        btnApagarTudo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnApagarTudo.setText("Apagar tudo");
        btnApagarTudo.setBorder(null);
        btnApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTudoActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 90, 30));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Adicionar nova tarefa:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Notes");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 11, -1, -1));

        btnAddTarefa.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTarefa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTarefa.setText("Adicionar");
        btnAddTarefa.setBorder(null);
        btnAddTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTarefaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddTarefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 30));

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        jPanel2.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 550, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 160));

        btnVerificar.setBackground(new java.awt.Color(153, 255, 255));
        btnVerificar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnVerificar.setText("Verificar lista");
        btnVerificar.setBorder(null);
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 100, 30));

        txtPainel.setBackground(new java.awt.Color(204, 255, 255));
        txtPainel.setColumns(20);
        txtPainel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPainel.setRows(5);
        jScrollPane1.setViewportView(txtPainel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 550, 200));

        lbTotalTarefas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbTotalTarefas.setText("0");
        jPanel1.add(lbTotalTarefas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 20));

        btnOrdenar.setBackground(new java.awt.Color(153, 255, 255));
        btnOrdenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnOrdenar.setText("Ordenar A-Z");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 551));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    GerenciadorTarefas gt = new GerenciadorTarefas();

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        btnVizualizar.doClick();
        int cod;
        cod = Integer.parseInt(JOptionPane.showInputDialog("Informe o código abaixo:"));

        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Confirme:",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gt.excluir(cod - 1);
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
        }
        btnVizualizar.doClick();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAddTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTarefaActionPerformed

        if (txtDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a descrição da tarefa, por favor.");
        } else {
            gt.addNovo(txtDescricao.getText());
            JOptionPane.showMessageDialog(null, "Tarefa criada com sucesso!");
            txtDescricao.requestFocus();
            txtDescricao.setText("");
            btnVizualizar.doClick();
        }

        int tamanho = gt.tarefa.size();
        String total = Integer.toString(tamanho);
        lbTotalTarefas.setText(total);

    }//GEN-LAST:event_btnAddTarefaActionPerformed

    private void btnVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarActionPerformed
        txtPainel.setText(gt.vizualizar());

    }//GEN-LAST:event_btnVizualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnVizualizar.doClick();
        int cod;
        String novoElemento;
        cod = Integer.parseInt(JOptionPane.showInputDialog("Informe o código abaixo:"));
        novoElemento = JOptionPane.showInputDialog("Nova tarefa:");
        gt.alterar((cod - 1), novoElemento);
        btnVizualizar.doClick();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTudoActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir tudo?", "Confirme:",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gt.tarefa.clear();
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
        }
        btnVizualizar.doClick();
    }//GEN-LAST:event_btnApagarTudoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        if (gt.tarefa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A lista de tarefas está vazia.");
        } else {
            JOptionPane.showMessageDialog(null, "A lista está preenchida.");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAddTarefa.doClick();
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        Collections.sort(gt.tarefa);
        btnVizualizar.doClick();
        
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarTarefas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarTarefas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarTarefas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarTarefas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTarefa;
    private javax.swing.JButton btnApagarTudo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVizualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lbTotalTarefas;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextArea txtPainel;
    // End of variables declaration//GEN-END:variables
}
